source 'https://github.com/CocoaPods/Specs.git'

 
 
workspace 'OpenCartKitExample'
inhibit_all_warnings!


target 'OpenCartKit_Example', :exclusive => true do
  pod "OpenCartKit", :path => "../"
  pod 'AFNetworking', '~> 2.5.4'
end

target 'OpenCartKit_Tests', :exclusive => true do
  pod "OpenCartKit", :path => "../"
  pod 'AFNetworking', '~> 2.5.4'	
 # pod 'Specta'
 # pod 'Expecta'
end
